# Generated by Django 2.2 on 2019-04-30 17:28

import ckeditor.fields
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=80)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DossierClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DossierEmploye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embauche', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.Departement')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('N', 'New'), ('W', 'Work In Progess'), ('D', 'Done'), ('C', 'Closed')], default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pm.DossierEmploye')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('start_at', models.DateField(blank=True)),
                ('end_at', models.DateField(blank=True)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.DossierClient')),
                ('project_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_lead', to='pm.DossierEmploye')),
                ('team', models.ManyToManyField(related_name='projects_dev', to='pm.DossierEmploye')),
            ],
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'entre'), (1, 'sortie'), (2, 'mission'), (3, 'pause')], default=0)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('temp', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='pm.User')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pm.Project')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='pm.User')),
            ],
        ),
        migrations.AddField(
            model_name='dossieremploye',
            name='employe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pm.User'),
        ),
        migrations.AddField(
            model_name='dossieremploye',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.JobTitle'),
        ),
        migrations.AddField(
            model_name='dossierclient',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pm.User'),
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Request'), (1, 'Confirmed'), (2, 'Rejected')], default=0)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.DossierEmploye')),
            ],
        ),
    ]
