# Generated by Django 2.2 on 2019-05-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_formation_departement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossierclient',
            options={'verbose_name': 'Client Profile'},
        ),
        migrations.AlterModelOptions(
            name='dossieremploye',
            options={'verbose_name': 'Staff Profile'},
        ),
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'verbose_name': 'Training'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='temp',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='message',
            name='dst',
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('message', 'message'), ('document', 'document'), ('notificaton', 'notification')], default='message', editable=False, max_length=12),
        ),
    ]
